services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5000:5000"
    environment:
      - API_GATEWAY_URL=http://api-gateway:8000
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
    # Aquí puedes agregar los otros servicios base

    # Microservicio de Autenticación
  auth-service:
    build: ./services/authentication
    container_name: auth-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mongodb://auth-db:27017/auth_db
    depends_on:
      - auth-db

  # Base de datos para el servicio de autenticación
  auth-db:
    image: mongo:latest
    container_name: auth-db
    ports:
      - "27017:27017"
    volumes:
      - auth_data:/data/db

  # --- Plantillas de Microservicios ---
  # Microservicio de Métricas
  metricas-service:
    build: ./services/metricas
    container_name: metricas-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DB}:5432/${POSTGRES_DB}
    depends_on:
      - metricas-db
  # Base de datos para el Microservicio de Métricas
  metricas-db:
    image: postgres
    container_name: metricas-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - metricas_data:/var/lib/postgresql/data
      
  # Microservicio de Análisis
  analisis-service:
    build: ./services/analisis
    container_name: analisis-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://user:password@analisis-db:5432/analisis_db
    depends_on:
      - analisis-db

  # Base de datos para el Microservicio de Análisis
  analisis-db:
    image: postgres
    container_name: analisis-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=analisis_db
    ports:
      - "5432:5432"
    volumes:
      - analisis_data:/var/lib/postgresql/data

  # Microservicio de Alertas
  alertas-service:
    build: ./services/alertas
    container_name: alertas-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://user:password@alertas-db:5432/alertas_db
    depends_on:
      - alertas-db

  # Base de datos para el Microservicio de Alertas
  alertas-db:
    image: redis
    container_name: alertas-db
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "6379:6379"
    volumes:
      - alertas_data:/var/lib/postgresql/data

volumes:
  auth_data:
  service1_data:
  metricas_data:
  analisis_data: